#!/bin/sh

. /lib/functions.sh
. /lib/functions/system.sh

# Config repository path
SMT_REPO=http://repo.smatec.com.vn/mgw7688

sed -i -e 's,https://downloads.openwrt.org/snapshots,'${SMT_REPO}',g' /etc/opkg/distfeeds.conf

# Included homeon-hs into the backup list
echo "/root/mgwp" >> /etc/sysupgrade.conf

# Config mpd and music folder
#mkdir -p /var/lib/mpd/music
#mkdir -p /var/lib/mpd/playlists
#mkdir -p /var/log/mpd
#mkdir -p /var/run/mpd

# Config mpd and music folder
# music_directory		
mkdir -p /mnt/mmcblk0p1/mgwp/audio
# playlist_directory		
mkdir -p /mnt/mmcblk0p1/mpd/playlists
# db_file			
touch /mnt/mmcblk0p1/mpd/database
# log_file			
touch /mnt/mmcblk0p1/mpd/log
# pid_file			
mkdir -p /var/run/mpd | touch /var/run/mpd/pid
# state_file			
touch /mnt/mmcblk0p1/mpd/state
# sticker_file			
touch /mnt/mmcblk0p1/mpd/sticker.sql

mv /etc/mpd.cfg /etc/mpd.conf

## If system is configured, then exit
[ "$(uci -q get system.@system[0].hostname)" = "MIRA-ENC" ] && exit 0

#[ "$(uci -q get system.@system[0].hostname)" = "MIRA" ] && exit 0

# Enable wifi
#uci set wireless.radio0.disabled='0'
#uci commit wireless

# Default 4G - qmi mode
uci set network.wan=interface
# uci set network.wan.ifname=wwan0
# uci set network.wan.proto='qmi'
# uci set network.wan.device='/dev/cdc-wdm0'
uci set network.wan.apn='m-wap'
uci set network.wan.modes='umts'
# Default is LAN
# uci set network.wan.auto='0'
# uci set network.wan.autoconnect='1'

# Default Lan with IP# 192.168.11.102
uci set network.lan=interface
uci set network.lan.type='bridge'
uci set network.lan.ifname='eth0'
uci set network.lan.proto='static'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.ip6assign='60'
# MIRA-ENC
uci set network.lan.ipaddr='192.168.1.199'
uci set network.lan.gateway='192.168.1.1'
# MIRA
#uci set network.lan.ipaddr='192.168.11.102'
#uci set network.lan.gateway='192.168.11.1'
uci set network.lan.dns='8.8.8.8 8.8.4.4'

uci commit network

# Disable DHCP at LAN
uci set dhcp.lan.ignore='1'
uci commit dhcp

# Set hostname
uci set system.@system[0].hostname='MIRA-ENC'

#uci set system.@system[0].hostname='MIRA'

# Change timezone
uci set system.@system[0].timezone='<+07>-7'
uci commit system

uci commit

exit 0
