#!/bin/sh

# Add new crontab
echo "Seting up crontab ... "
echo "*/2 * * * * /root/internet-keep-alive/internet-keep-alive.sh" > /etc/crontabs/root
echo "*/1 * * * * /usr/bin/mgwp_monitor" >> /etc/crontabs/root
#echo "*/1 * * * * /usr/bin/mgwp_mpd_monitor" >> /etc/crontabs/root
echo "00 08 * * * find /mnt/mmcblk0p1/mgwp/*.txt -mtime +30 -exec rm -r {} \;" >> /etc/crontabs/root
#echo "3 * * * * /etc/init.d/homeon-hzg restart" >> /etc/crontabs/root
exit 0