#!/bin/sh

uci set system.@system[0].os_version='mgw-os v3.0.0.6'
uci set system.@system[0].os_builddate='2023.12.25 08:00:00'
uci set system.@system[0].cpu_processor='ARM Cortex-A53'
uci set system.@system[0].cpu_freq='1.25GHz'
uci set system.@system[0].cpu_core='4'
uci set system.@system[0].gpu_processor='ARM Mali-T720 MP1'
uci set system.@system[0].ram_cap='1.0GB'
uci set system.@system[0].emmc_cap='16.0GB'

#Add LAN status led config
echo "config led" >> /etc/config/system
uci set system.@led[1].name='LAN'
uci set system.@led[1].sysfs='green:lan1'
uci set system.@led[1].trigger='netdev'
uci set system.@led[1].dev='eth0'
uci add_list system.@led[1].mode='link' 
uci add_list system.@led[1].mode='tx' 
uci add_list system.@led[1].mode='rx' 
uci commit system

exit 0